spring.application.name=ddait

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.url=${DB_URL}
spring.jpa.hibernate.ddl-auto=update

spring.security.oauth2.client.registration.google.client-id=${CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${USER_EMAIL}
spring.mail.password=${APP_PW}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

jwt.secretKey=${SK}

jwt.access.expiration=3600000
jwt.access.header=Authorization

jwt.refresh.expiration=1209600000
jwt.refresh.header=Authorization-refresh


# 1. ???? ?? ?? ?? ?? (?? ??? ??? ?? ?)
logging.level.root=INFO

# 2. ? ??(????, ???)? ??? ?? ???
# ??? ??? fiveonestudy.ddait? ??
logging.level.fiveonestudy.ddait=DEBUG

# 3. ??? ?/??? ?? ?? ?? (JSON ?? ?? ??)
logging.level.org.springframework.web=DEBUG

# 4. ???? ?? ?? (JWT ?? ???? ???? ??)
logging.level.org.springframework.security=DEBUG

# 5. DB ?? ? ???? ?? (??? ?? ?? ??)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# 2. SQL? ??? ??? ?? ??
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 3. DB ?? ?? (??? ???? DB? ?? ??)
# H2 ?? ?:
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# MySQL ?? ?:
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# 1. JSON? Snake Case? Java? Camel Case ?? ?? ??
spring.jackson.property-naming-strategy=LOWER_CAMEL_CASE

# 2. ??(LocalDate) ??? ???? ? ?? ??? ?? ???(yyyy-MM-dd)? ??
spring.jackson.serialization.write-dates-as-timestamps=false